[package]
authors = ["T.J. Telan <t.telan@gmail.com>"]
categories = ["parser-implementations", "encoding"]
description = "A parser for git repo urls based on url crate"
documentation = "https://docs.rs/git-url-parse"
edition = "2018"
keywords = ["git", "url", "parsing"]
license = "MIT"
name = "git-url-parse"
readme = "README.md"
repository = "https://github.com/tjtelan/git-url-parse-rs"
version = "0.1.0"

[badges.maintenance]
status = "actively-developed"

[dependencies]
log = "0.4"
url = "2.1"
strum = "0.17"
strum_macros = "0.17"
anyhow = "1.0"
regex = "1.3"
env_logger = "0.7"

[dev-dependencies]
env_logger = "0.7"
