[package]
name = "git-url-parse"
version = "0.0.1"
authors = ["T.J. Telan <t.telan@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
url = "2.1"
strum = "0.17"
strum_macros = "0.17"
anyhow = "1.0"
regex = "1.3"

[dev-dependencies]
env_logger = "0.7"
